### ISSUE TITLE
Make report button size and DropDown item size larger

### ISSUE THREAD

**Issue by LakshmiCHAI** [chailmis/chailmis-android#153] opened 2015-03-25 17:47 UTC
Buttons for selecting month are very small and difficult to select a specific month, make these bigger

Severity: High

**Comment by reneeorser** [comment] 2015-03-26 13:24
Duplicate of 145, but high instead of low. Will delete #145

**Comment by chai-lmis** [comment] 2015-04-24 07:57
can this button be made slightly bigger still (for clumsy fingers like mine)

**Comment by cameotisha** [comment] 2015-04-27 12:57
- Months and years in the drop down list still appear small to a person who has not used a tablet or smart phone before
Test
- Tried selecting month and year with my thumb and was able to select the required year

Unable to test
------
- When there are many years, how scroll works.
_-Not sure how small the buttons were before. test not conclusive

**Comment by chai-lmis** [comment] 2015-04-27 13:05
Months and years drop down should be enlarged - large  enough for someone to select the correct month on the first attempt- comfortable

**Comment by cameotisha** [comment] 2015-04-28 12:20
Tests
-------
- Dropdown list bigger and easier to click
- Column labels have been wrapped and space between each column is now uniform
- Test Result: Passed

**Closed** 2015-05-06 03:43 UTC
Labels: Client QA, Estimate:Small, FEATURE, Severity: High
