### ISSUE TITLE
The error "Unfortunately DHIS has stopped"  pops up on the screen every few minutes, once "ok" is clicked it goes back to the page previously displayed and works without issues until the error pops up again

### ISSUE THREAD

**Issue by chai-lmis** [chailmis/chailmis-android#160] opened 2015-04-16 09:08 UTC

**Comment by chai-lmis** [comment] 2015-04-24 08:07
This does not occur anymore after the latest apk update

**Comment by chai-lmis** [comment] 2015-04-24 15:50
crashing started again after the production apk was downloaded

**Comment by cvaldez519** [comment] 2015-04-30 17:32
TESTED 
Performed test using both development and production apk
1. Used app for about 5 minutes running reports, and enter various other data the app while online, no error. 
2. Disconnected app and while offline work on it for 5 minutes same as above, no error. 
3. Reconnected app worked on it for 5 minutes as above, no error. 

Since I can't reproduce it I'm closing it.

**Comment by karlwbrown** [comment] 2015-05-04 20:09
Moving this to Ready for QA, so CHAI can test accordingly.

**Closed** 2015-05-06 03:38 UTC
Labels: BUG, Estimate: Medium, Ready for QA, Severity: Critical
