### ISSUE TITLE
Receiving an allocation causes the app to crash

### ISSUE THREAD

**Issue by LakshmiCHAI** [chailmis/chailmis-android#130] opened 2015-03-12 17:44 UTC
Severity: Critical

**Comment by JamesMura** [comment] 2015-03-14 10:54
@LakshmiCHAI Is it possible to share the login credentials used when this occurs and a simple brief on how to recreate this . I am finding it hard to recreate this specific issue.

**Comment by reneeorser** [comment] 2015-04-09 09:15
8 April QA comment: Receiving an allocation doesn’t crash the app anymore, but I noticed a bug; when an allocation is successfully received,  the next page displayed is the same Received page with the just received allocation id and the populated commodities, you need to manually exit the page for this to disappear. An allocation received successfully should display the home page with the new SOH for the commodities on the bar chart (where applicable).

**Comment by gigix** [comment] 2015-04-14 07:44
Available allocation ID for user "job_tw":
NA0407

**Comment by chai-lmis** [comment] 2015-04-16 13:52
I have tried receiving an allocation on 3 different facilities and this still crashes the app, this happens when you click the allocation alert or go to the Receive activity

**Comment by karlwbrown** [comment] 2015-05-05 22:30
not sure why this was marked as a feature.

**Comment by chai-lmis** [comment] 2015-05-06 06:55
This bug seems to be fixed now as i can receive allocations successfully without the app crashing

**Comment by cvaldez519** [comment] 2015-05-07 18:25
CONFIRMED

**Closed by cvaldez519** 2015-05-07 18:25 UTC
Labels: BUG, Estimate:Large, Severity: Critical
